version: "3.7"

services:  
  # -----------------------------
  # postgres database
  # -----------------------------
  postgres:
    container_name: quera-postgres
    image: postgres:13.3
    restart: unless-stopped
    volumes: 
      - quera:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    networks:
      - quera
# -----------------------------
# networks
# -----------------------------
networks:
  quera:
    external: true
# -----------------------------        
# volumes
# -----------------------------
volumes: 
  quera:
    name: quera 
    driver: local

